backend:
  name: git-gateway
  branch: master
  site_domain: clever-longma-6b22c6.netlify.app
  base_url: https://api.netlify.com

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  # 1 — sponsors (unchanged) -----------------------------
  - name: "sponsors"
    label: "Sponsors"
    folder: "src/data/sponsors"
    create: true
    slug: "{{alt}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Sponsor Name (for Alt Text)", name: "alt", widget: "string" }
      - { label: "Logo",           name: "src",          widget: "image" }
      - { label: "Tooltip Text",   name: "tooltipText",  widget: "text" }
      - { label: "Website URL",    name: "websiteUrl",   widget: "string" }

  # 2 — testimonials (fixed) -----------------------------
  - label: "Testimonials"
    name:  "testimonials"
    files:
      - file: "src/data/testimonials.json"
        label: "Testimonials List"
        name:  "list"                 # REQUIRED
        format: "json"
        extension: "json"
        widget: "list"                # root-level array
        fields:
          - { label: "Person's Name", name: "name",  widget: "string" }
          - { label: "Quote",         name: "quote", widget: "text" }

  # 3 — services (unchanged) -----------------------------
  - name: "services"
    label: "Classes & Services"
    folder: "src/data/services"
    create: true
    slug: "{{text}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Service Name", name: "text", widget: "string" }
      - { label: "Icon (FontAwesome)", name: "icon", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Support Service", "Educational Course", "QQI Module"]